<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="9.0.1">
      <!-- TODO: bump to Version="12.0.3" once we drop the net48 target -->
      <PrivateAssets>none</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
